#!/usr/bin/env zsh
if [[ -z $STOW_FOLDERS ]]; then
    STOW_FOLDERS="bin,brew,direnv,git-setup,nvim,tmux,tree-sitter,zsh,rizin"
fi

if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/personal/.dotfiles
fi

STOW_FOLDERS=$STOW_FOLDERS DOTFILES=$DOTFILES $DOTFILES/install
