# captype
# Autogenerated from man page /Applications/Wireshark.app/Contents/Resources/share/man/man1/captype.1
complete -c captype -s h -l help -d 'Print the version number and options and exit'
complete -c captype -s v -l version -d 'Print the full version information and exit'
complete -c captype -l log-level
complete -c captype -l log-fatal
complete -c captype -l log-domains
complete -c captype -l log-debug
complete -c captype -l log-noisy
complete -c captype -l log-file

