# cat
# Autogenerated from man page /usr/local/opt/coreutils/libexec/gnuman/man1/cat.1
complete -c cat -s A -l show-all -d 'equivalent to -vET'
complete -c cat -l number-nonblank -d 'number nonempty output lines, overrides -n'
complete -c cat -s E -l show-ends -d 'display $ at end of each line'
complete -c cat -l number -d 'number all output lines'
complete -c cat -l squeeze-blank -d 'suppress repeated empty output lines'
complete -c cat -s T -l show-tabs -d 'display TAB characters as ^I'
complete -c cat -l show-nonprinting -d 'use ^ and M- notation, except for LFD and TAB'
complete -c cat -l help -d 'display this help and exit'
complete -c cat -l version -d 'output version information and exit EXAMPLES'

