# comm
# Autogenerated from man page /usr/local/opt/coreutils/libexec/gnuman/man1/comm.1
complete -c comm -l check-order -d 'check that the input is correctly sorted, even if all input lines are pairable'
complete -c comm -l nocheck-order -d 'do not check that the input is correctly sorted'
complete -c comm -l output-delimiter -d 'separate columns with STR'
complete -c comm -l total -d 'output a summary'
complete -c comm -s z -l zero-terminated -d 'line delimiter is NUL, not newline'
complete -c comm -l help -d 'display this help and exit'
complete -c comm -l version -d 'output version information and exit'

