# dftest
# Autogenerated from man page /Applications/Wireshark.app/Contents/Resources/share/man/man1/dftest.1
complete -c dftest -l log-level
complete -c dftest -l log-fatal
complete -c dftest -l log-domains
complete -c dftest -l log-debug
complete -c dftest -l log-noisy
complete -c dftest -l log-file

