# echo
# Autogenerated from man page /usr/local/opt/coreutils/libexec/gnuman/man1/echo.1
complete -c echo -s e -d 'enable interpretation of backslash escapes'
complete -c echo -s E -d 'disable interpretation of backslash escapes (default)'
complete -c echo -l help -d 'display this help and exit'
complete -c echo -l version -d 'output version information and exit '

