# env
# Autogenerated from man page /usr/local/opt/coreutils/libexec/gnuman/man1/env.1
complete -c env -l ignore-environment -d 'start with an empty environment'
complete -c env -l null -d 'end each output line with NUL, not newline'
complete -c env -l unset -d 'remove variable from the environment'
complete -c env -s C -l chdir -d 'change working directory to DIR'
complete -c env -l split-string -d 'process and split S into separate arguments; used to pass multiple arguments …'
complete -c env -l block-signal -d 'block delivery of SIG signal(s) to COMMAND'
complete -c env -l default-signal -d 'reset handling of SIG signal(s) to the default'
complete -c env -l ignore-signal -d 'set handling of SIG signal(s) to do nothing'
complete -c env -l list-signal-handling -d 'list non default signal handling to stderr'
complete -c env -l debug -d 'print verbose information for each processing step'
complete -c env -l help -d 'display this help and exit'
complete -c env -l version -d 'output version information and exit . PP A mere - implies -i'
complete -c env -o S/--split-string -d The

