# etwdump
# Autogenerated from man page /Applications/Wireshark.app/Contents/Resources/share/man/man1/etwdump.1
complete -c etwdump -l help -d 'Print program arguments'
complete -c etwdump -l version -d 'Print program version'
complete -c etwdump -l extcap-interfaces -d 'List available interfaces'
complete -c etwdump -l extcap-interface -d 'Use specified interfaces'
complete -c etwdump -l extcap-dlts -d 'List DLTs of specified interface'
complete -c etwdump -l extcap-config -d 'List configuration options of specified interface'
complete -c etwdump -l capture -d 'Start capturing from specified interface save saved it in place specified by …'
complete -c etwdump -l fifo -d 'Save captured packet to file or send it through pipe'
complete -c etwdump -l iue -d 'Choose if the undecidable event is included'
complete -c etwdump -l etlfile -d 'Select etl file to display in Wireshark'
complete -c etwdump -l params -d 'Input providers, keyword and level filters for the etl file and live session'

