# expr
# Autogenerated from man page /usr/local/opt/coreutils/libexec/gnuman/man1/expr.1
complete -c expr -l help -d 'display this help and exit'
complete -c expr -l version -d 'output version information and exit '

