# fold
# Autogenerated from man page /usr/local/opt/coreutils/libexec/gnuman/man1/fold.1
complete -c fold -l bytes -d 'count bytes rather than columns'
complete -c fold -l spaces -d 'break at spaces'
complete -c fold -l width -d 'use WIDTH columns instead of 80'
complete -c fold -l help -d 'display this help and exit'
complete -c fold -l version -d 'output version information and exit AUTHOR Written by David MacKenzie'

