# gh-auth-token
# Autogenerated from man page /usr/local/share/man/man1/gh-auth-token.1
complete -c gh-auth-token -s h -l hostname -d 'The hostname of the GitHub instance authenticated with SEE ALSO'

