# gh-issue-unpin
# Autogenerated from man page /usr/local/share/man/man1/gh-issue-unpin.1
complete -c gh-issue-unpin -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format EXAMPLE # Unpin …'

