# gh-project-delete
# Autogenerated from man page /usr/local/share/man/man1/gh-project-delete.1
complete -c gh-project-delete -l format -d 'Output format: {json}'
complete -c gh-project-delete -l owner -d 'Login of the owner.  Use "@me" for the current user'

