# gh-run-delete
# Autogenerated from man page /usr/local/share/man/man1/gh-run-delete.1
complete -c gh-run-delete -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format EXAMPLE # Intera…'

