# git-worktree
# Autogenerated from man page /usr/local/share/man/man1/git-worktree.1
complete -c git-worktree -l orphan -d 'With add, make the new worktree and index empty, associating the worktree wit…'
complete -c git-worktree -o f/--force -d list

