# git-branch
# Autogenerated from man page /usr/local/share/man/man1/git-branch.1
complete -c git-branch -l omit-empty -d 'Do not print a newline after formatted refs where the format expands to the e…'

