# git-diff-tree
# Autogenerated from man page /usr/local/share/man/man1/git-diff-tree.1
complete -c git-diff-tree -l default-prefix -d 'Use the default source and destination prefixes ("a/" and "b/")'

