# id
# Autogenerated from man page /usr/local/opt/coreutils/libexec/gnuman/man1/id.1
complete -c id -s Z -l context -d 'print only the security context of the process'
complete -c id -l group -d 'print only the effective group ID'
complete -c id -l groups -d 'print all group IDs'
complete -c id -l name -d 'print a name instead of a number, for -ugG'
complete -c id -l real -d 'print the real ID instead of the effective ID, with -ugG'
complete -c id -l user -d 'print only the effective user ID'
complete -c id -s z -l zero -d 'delimit entries with NUL characters, not whitespace; P not permitted in defau…'
complete -c id -l help -d 'display this help and exit'
complete -c id -l version -d 'output version information and exit'

