# join
# Autogenerated from man page /usr/local/opt/coreutils/libexec/gnuman/man1/join.1
complete -c join -s i -l ignore-case -d 'ignore differences in case when comparing fields'
complete -c join -l check-order -d 'check that the input is correctly sorted, even if all input lines are pairable'
complete -c join -l nocheck-order -d 'do not check that the input is correctly sorted'
complete -c join -l header -d 'treat the first line in each file as field headers, print them without trying…'
complete -c join -s z -l zero-terminated -d 'line delimiter is NUL, not newline'
complete -c join -l help -d 'display this help and exit'
complete -c join -l version -d 'output version information and exit'

