# kill
# Autogenerated from man page /usr/local/opt/coreutils/libexec/gnuman/man1/kill.1
complete -c kill -l list -d 'list signal names, or convert signal names to/from numbers'
complete -c kill -s t -l table -d 'print a table of signal information'
complete -c kill -l help -d 'display this help and exit'
complete -c kill -l signal -o SIGNAL -d 'specify the name or number of the signal to be sent'
complete -c kill -l version -d 'output version information and exit'

