# kubeadm-init-phase-upload-config
# Autogenerated from man page /usr/local/share/man/man1/kubeadm-init-phase-upload-config.1
complete -c kubeadm-init-phase-upload-config -l azure-container-registry-config -d '	Path to the file containing Azure container registry configuration informati…'
complete -c kubeadm-init-phase-upload-config -l rootfs -d '	[EXPERIMENTAL] The path to the \'real\' host root filesystem'
complete -c kubeadm-init-phase-upload-config -l version -d '	--version, --version=raw prints version information and quits; --version=vX'

