# kubeadm-config
# Autogenerated from man page /usr/local/share/man/man1/kubeadm-config.1
complete -c kubeadm-config -l kubeconfig -d '	The kubeconfig file to use when talking to the cluster'
complete -c kubeadm-config -l azure-container-registry-config -d '	Path to the file containing Azure container registry configuration informati…'
complete -c kubeadm-config -l rootfs -d '	[EXPERIMENTAL] The path to the \'real\' host root filesystem'
complete -c kubeadm-config -l version -d '	--version, --version=raw prints version information and quits; --version=vX'

