# kubeadm-init-phase-kubeconfig
# Autogenerated from man page /usr/local/share/man/man1/kubeadm-init-phase-kubeconfig.1
complete -c kubeadm-init-phase-kubeconfig -l azure-container-registry-config -d '	Path to the file containing Azure container registry configuration informati…'
complete -c kubeadm-init-phase-kubeconfig -l rootfs -d '	[EXPERIMENTAL] The path to the \'real\' host root filesystem'
complete -c kubeadm-init-phase-kubeconfig -l version -d '	--version, --version=raw prints version information and quits; --version=vX'

