# kubeadm-config-print-reset-defaults
# Autogenerated from man page /usr/local/share/man/man1/kubeadm-config-print-reset-defaults.1
complete -c kubeadm-config-print-reset-defaults -l component-configs -d '	A comma-separated list for component config API objects to print the default…'
complete -c kubeadm-config-print-reset-defaults -l azure-container-registry-config -d '	Path to the file containing Azure container registry configuration informati…'
complete -c kubeadm-config-print-reset-defaults -l kubeconfig -d '	The kubeconfig file to use when talking to the cluster'
complete -c kubeadm-config-print-reset-defaults -l rootfs -d '	[EXPERIMENTAL] The path to the \'real\' host root filesystem'
complete -c kubeadm-config-print-reset-defaults -l version -d '	--version, --version=raw prints version information and quits; --version=vX'

