# kubeadm-join-phase
# Autogenerated from man page /usr/local/share/man/man1/kubeadm-join-phase.1
complete -c kubeadm-join-phase -l azure-container-registry-config -d '	Path to the file containing Azure container registry configuration informati…'
complete -c kubeadm-join-phase -l rootfs -d '	[EXPERIMENTAL] The path to the \'real\' host root filesystem'
complete -c kubeadm-join-phase -l version -d '	--version, --version=raw prints version information and quits; --version=vX'

