# kubeadm-init-phase-certs-sa
# Autogenerated from man page /usr/local/share/man/man1/kubeadm-init-phase-certs-sa.1
complete -c kubeadm-init-phase-certs-sa -l cert-dir -d '	The path where to save and store the certificates'
complete -c kubeadm-init-phase-certs-sa -l azure-container-registry-config -d '	Path to the file containing Azure container registry configuration informati…'
complete -c kubeadm-init-phase-certs-sa -l rootfs -d '	[EXPERIMENTAL] The path to the \'real\' host root filesystem'
complete -c kubeadm-init-phase-certs-sa -l version -d '	--version, --version=raw prints version information and quits; --version=vX'

