# kubeadm-alpha
# Autogenerated from man page /usr/local/share/man/man1/kubeadm-alpha.1
complete -c kubeadm-alpha -l azure-container-registry-config -d '	Path to the file containing Azure container registry configuration informati…'
complete -c kubeadm-alpha -l rootfs -d '	[EXPERIMENTAL] The path to the \'real\' host root filesystem'
complete -c kubeadm-alpha -l version -d '	--version, --version=raw prints version information and quits; --version=vX'

