# ln
# Autogenerated from man page /usr/local/opt/coreutils/libexec/gnuman/man1/ln.1
complete -c ln -l backup -d 'make a backup of each existing destination file'
complete -c ln -s b -d 'like --backup but does not accept an argument'
complete -c ln -s d -l directory -d 'allow the superuser to attempt to hard link directories (note: will probably …'
complete -c ln -l force -d 'remove existing destination files'
complete -c ln -l interactive -d 'prompt whether to remove destinations'
complete -c ln -l logical -d 'dereference TARGETs that are symbolic links'
complete -c ln -l no-dereference -d 'treat LINK_NAME as a normal file if it is a symbolic link to a directory'
complete -c ln -l physical -d 'make hard links directly to symbolic links'
complete -c ln -s r -l relative -d 'with -s, create links relative to link location'
complete -c ln -l symbolic -d 'make symbolic links instead of hard links'
complete -c ln -s S -l suffix -d 'override the usual backup suffix'
complete -c ln -s t -l target-directory -d 'specify the DIRECTORY in which to create the links'
complete -c ln -s T -l no-target-directory -d 'treat LINK_NAME as a normal file always'
complete -c ln -l verbose -d 'print name of each linked file'
complete -c ln -l help -d 'display this help and exit'
complete -c ln -l version -d 'output version information and exit '

