# mergecap
# Autogenerated from man page /Applications/Wireshark.app/Contents/Resources/share/man/man1/mergecap.1
complete -c mergecap -s a -d 'Causes the frame timestamps to be ignored, writing all packets from the first…'
complete -c mergecap -s F -d 'Sets the file format of the output capture file'
complete -c mergecap -s h -l help -d 'Prints the version and options and exits'
complete -c mergecap -s I -d 'Sets the Interface Description Block (IDB) merge mode to use during merging'
complete -c mergecap -s s -d 'Sets the snapshot length to use when writing the data'
complete -c mergecap -s v -l version -d 'Print the version and exit'
complete -c mergecap -s V -d 'Causes mergecap to print a number of messages while it\'s working'
complete -c mergecap -s w -d 'Sets the output filename.  If the name is \\fB-, stdout will be used'
complete -c mergecap -l log-level
complete -c mergecap -l log-fatal
complete -c mergecap -l log-domains
complete -c mergecap -l log-debug
complete -c mergecap -l log-noisy
complete -c mergecap -l log-file

