# mmdbresolve
# Autogenerated from man page /Applications/Wireshark.app/Contents/Resources/share/man/man1/mmdbresolve.1
complete -c mmdbresolve -s f -d 'Path to a MaxMind Database file.  Multiple databases may be specified'

