# nl
# Autogenerated from man page /usr/local/opt/coreutils/libexec/gnuman/man1/nl.1
complete -c nl -l body-numbering -d 'use STYLE for numbering body lines'
complete -c nl -l section-delimiter -d 'use CC for logical page delimiters'
complete -c nl -l footer-numbering -d 'use STYLE for numbering footer lines'
complete -c nl -l header-numbering -d 'use STYLE for numbering header lines'
complete -c nl -l line-increment -d 'line number increment at each line'
complete -c nl -l join-blank-lines -d 'group of NUMBER empty lines counted as one'
complete -c nl -l number-format -d 'insert line numbers according to FORMAT'
complete -c nl -l no-renumber -d 'do not reset line numbers for each section'
complete -c nl -l number-separator -d 'add STRING after (possible) line number'
complete -c nl -l starting-line-number -d 'first line number for each section'
complete -c nl -l number-width -d 'use NUMBER columns for line numbers'
complete -c nl -l help -d 'display this help and exit'
complete -c nl -l version -d 'output version information and exit '

