# od
# Autogenerated from man page /usr/local/opt/coreutils/libexec/gnuman/man1/od.1
complete -c od -l address-radix -d 'output format for file offsets; RADIX is one of [doxn], for Decimal, Octal, H…'
complete -c od -l endian -d 'swap input bytes according the specified order'
complete -c od -l skip-bytes -d 'skip BYTES input bytes first'
complete -c od -l read-bytes -d 'limit dump to BYTES input bytes'
complete -c od -s S -l strings -d 'show only NUL terminated strings of at least BYTES (3) printable characters'
complete -c od -l format -d 'select output format or formats'
complete -c od -l output-duplicates -d 'do not use * to mark line suppression'
complete -c od -s w -l width -d 'output BYTES bytes per output line; 32 is implied when BYTES is not specified'
complete -c od -l traditional -d 'accept arguments in third form above'
complete -c od -l help -d 'display this help and exit'
complete -c od -l version -d 'output version information and exit '
complete -c od -s l -d 'same as -t dL, select decimal longs'
complete -c od -s o -d 'same as -t o2, select octal 2-byte units'
complete -c od -s x -d 'same as -t x2, select hexadecimal 2-byte units '

