# paste
# Autogenerated from man page /usr/local/opt/coreutils/libexec/gnuman/man1/paste.1
complete -c paste -l delimiters -d 'reuse characters from LIST instead of TABs'
complete -c paste -l serial -d 'paste one file at a time instead of in parallel'
complete -c paste -s z -l zero-terminated -d 'line delimiter is NUL, not newline'
complete -c paste -l help -d 'display this help and exit'
complete -c paste -l version -d 'output version information and exit AUTHOR Written by David M'

