# pathchk
# Autogenerated from man page /usr/local/opt/coreutils/libexec/gnuman/man1/pathchk.1
complete -c pathchk -l portability -d 'check for all POSIX systems (equivalent to -p -P)'
complete -c pathchk -l help -d 'display this help and exit'
complete -c pathchk -l version -d 'output version information and exit AUTHOR Written by Paul Eggert, David MacK…'

