# printf
# Autogenerated from man page /usr/local/opt/coreutils/libexec/gnuman/man1/printf.1
complete -c printf -l help -d 'display this help and exit'
complete -c printf -l version -d 'output version information and exit '

