# pwd
# Autogenerated from man page /usr/local/opt/coreutils/libexec/gnuman/man1/pwd.1
complete -c pwd -l logical -d 'use PWD from environment, even if it contains symlinks'
complete -c pwd -l physical -d 'avoid all symlinks'
complete -c pwd -l help -d 'display this help and exit'
complete -c pwd -l version -d 'output version information and exit'

