# randpkt
# Autogenerated from man page /Applications/Wireshark.app/Contents/Resources/share/man/man1/randpkt.1
complete -c randpkt -s b -d 'Default 5000'
complete -c randpkt -s c -d 'Default 1000'
complete -c randpkt -s t -d 'Default Ethernet II frame'
complete -c randpkt -l log-level
complete -c randpkt -l log-fatal
complete -c randpkt -l log-domains
complete -c randpkt -l log-debug
complete -c randpkt -l log-noisy
complete -c randpkt -l log-file

