# reordercap
# Autogenerated from man page /Applications/Wireshark.app/Contents/Resources/share/man/man1/reordercap.1
complete -c reordercap -s n -d 'When the -n option is used, reordercap will not write out the output file if …'
complete -c reordercap -s v -d 'Print the version and exit'
complete -c reordercap -l log-level
complete -c reordercap -l log-fatal
complete -c reordercap -l log-domains
complete -c reordercap -l log-debug
complete -c reordercap -l log-noisy
complete -c reordercap -l log-file

