# test
# Autogenerated from man page /usr/local/opt/coreutils/libexec/gnuman/man1/test.1
complete -c test -l help -d 'display this help and exit'
complete -c test -l version -d 'output version information and exit '
complete -c test -s a -d 'both EXPRESSION1 and EXPRESSION2 are true'
complete -c test -s o -d 'either EXPRESSION1 or EXPRESSION2 is true'
complete -c test -o eq -d 'INTEGER1 is equal to INTEGER2'
complete -c test -o ge -d 'INTEGER1 is greater than or equal to INTEGER2'
complete -c test -o gt -d 'INTEGER1 is greater than INTEGER2'
complete -c test -o le -d 'INTEGER1 is less than or equal to INTEGER2'
complete -c test -o lt -d 'INTEGER1 is less than INTEGER2'
complete -c test -o ne -d 'INTEGER1 is not equal to INTEGER2'
complete -c test -o ef -d 'FILE1 and FILE2 have the same device and inode numbers'
complete -c test -o nt -d 'FILE1 is newer (modification date) than FILE2'
complete -c test -o ot -d 'FILE1 is older than FILE2'
complete -c test -s N -d 'FILE exists and has been modified since it was last read'

