# tr
# Autogenerated from man page /usr/local/opt/coreutils/libexec/gnuman/man1/tr.1
complete -c tr -l complement -d 'use the complement of ARRAY1'
complete -c tr -l delete -d 'delete characters in ARRAY1, do not translate'
complete -c tr -l squeeze-repeats -d 'replace each sequence of a repeated character that is listed in the last spec…'
complete -c tr -s t -l truncate-set1 -d 'first truncate ARRAY1 to length of ARRAY2'
complete -c tr -l help -d 'display this help and exit'
complete -c tr -l version -d 'output version information and exit '

