# truncate
# Autogenerated from man page /usr/local/opt/coreutils/libexec/gnuman/man1/truncate.1
complete -c truncate -l no-create -d 'do not create any files'
complete -c truncate -s o -l io-blocks -d 'treat SIZE as number of IO blocks instead of bytes'
complete -c truncate -l reference -d 'base size on RFILE'
complete -c truncate -l size -d 'set or adjust the file size by SIZE bytes'
complete -c truncate -l help -d 'display this help and exit'
complete -c truncate -l version -d 'output version information and exit'

