# uname
# Autogenerated from man page /usr/local/opt/coreutils/libexec/gnuman/man1/uname.1
complete -c uname -l all -d 'print all information, in the following order, except omit -p and -i if unkno…'
complete -c uname -l kernel-name -d 'print the kernel name'
complete -c uname -l nodename -d 'print the network node hostname'
complete -c uname -l kernel-release -d 'print the kernel release'
complete -c uname -l kernel-version -d 'print the kernel version'
complete -c uname -l machine -d 'print the machine hardware name'
complete -c uname -l processor -d 'print the processor type (non-portable)'
complete -c uname -s i -l hardware-platform -d 'print the hardware platform (non-portable)'
complete -c uname -l operating-system -d 'print the operating system'
complete -c uname -l help -d 'display this help and exit'
complete -c uname -l version -d 'output version information and exit AUTHOR Written by David MacKenzie'

