# uniq
# Autogenerated from man page /usr/local/opt/coreutils/libexec/gnuman/man1/uniq.1
complete -c uniq -l count -d 'prefix lines by the number of occurrences'
complete -c uniq -l repeated -d 'only print duplicate lines, one for each group'
complete -c uniq -l all-repeated -d 'like -D, but allow separating groups with an empty line; METHOD={none(default…'
complete -c uniq -l skip-fields -d 'avoid comparing the first N fields'
complete -c uniq -l group -d 'show all items, separating groups with an empty line; METHOD={separate(defaul…'
complete -c uniq -l ignore-case -d 'ignore differences in case when comparing'
complete -c uniq -l skip-chars -d 'avoid comparing the first N characters'
complete -c uniq -l unique -d 'only print unique lines'
complete -c uniq -s z -l zero-terminated -d 'line delimiter is NUL, not newline'
complete -c uniq -s w -l check-chars -d 'compare no more than N characters in lines'
complete -c uniq -l help -d 'display this help and exit'
complete -c uniq -l version -d 'output version information and exit'

