# uptime
# Autogenerated from man page /usr/local/opt/coreutils/libexec/gnuman/man1/uptime.1
complete -c uptime -l help -d 'display this help and exit'
complete -c uptime -l version -d 'output version information and exit AUTHOR Written by Joseph Arceneaux, David…'

