# wc
# Autogenerated from man page /usr/local/opt/coreutils/libexec/gnuman/man1/wc.1
complete -c wc -l bytes -d 'print the byte counts'
complete -c wc -l chars -d 'print the character counts'
complete -c wc -l lines -d 'print the newline counts'
complete -c wc -l files0-from -d 'read input from the files specified by NUL-terminated names in file F; If F i…'
complete -c wc -l max-line-length -d 'print the maximum display width'
complete -c wc -l words -d 'print the word counts'
complete -c wc -l total -d 'when to print a line with total counts; WHEN can be: auto, always, only, never'
complete -c wc -l help -d 'display this help and exit'
complete -c wc -l version -d 'output version information and exit AUTHOR Written by Paul Rubin and David Ma…'

